# Generated by Django 5.0.6 on 2024-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securityId', models.CharField(max_length=20, unique=True)),
                ('instrumentType', models.CharField(max_length=200)),
                ('tradeDate', models.DateField()),
                ('direction', models.CharField(max_length=100)),
                ('notional', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numberContracts', models.IntegerField()),
                ('price', models.FloatField()),
                ('username', models.CharField(max_length=300)),
                ('comment', models.TextField(blank=True, max_length=800, null=True)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(blank=True, max_length=300, null=True)),
                ('spread', models.FloatField()),
            ],
        ),
    ]
