# Generated by Django 5.0.6 on 2024-06-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
