# Generated by Django 5.0.6 on 2024-06-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_trades_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='strategyID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='numberContracts',
            field=models.IntegerField(blank=True),
        ),
    ]
