# Generated by Django 5.0.6 on 2024-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_securityid_trade_securityid_remove_trade_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='instrumentType',
            field=models.CharField(choices=[('CDS', 'CDS'), ('Bonds', 'Bonds'), ('Futures', 'Futures'), ('FX', 'FX')], default='CDS', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='tradeDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
