# Generated by Django 5.0.6 on 2024-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_trade_instrumenttype_trade_tradedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='numberContracts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
