# Generated by Django 5.0.6 on 2024-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_trade_notional_alter_trade_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('Buy', 'Buy (Short risk)'), ('Sell', 'Sell (Long)')], default='Buy', max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='notional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='spread',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
